# Generated by Django 5.0.6 on 2024-06-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=55),
        ),
    ]
