# Generated by Django 5.0.6 on 2024-06-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
    ]
